name       : dvdauthor
version    : 0.7.2
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/dvdauthor/dvdauthor-0.7.2.tar.gz : 3020a92de9f78eb36f48b6f22d5a001c47107826634a785a62dfcd080f612eb7
license    : GPL-2.0
component  : multimedia.video
summary    : A set of tools to help you generate DVD files to be played back on a standalone DVD player
description: |
    DVDAuthor is a set of tools to help you author the file and directory
    structure of a DVD-Video disc, including programmatic commands for 
    implementing interactive behaviour.
builddeps  :
    - pkgconfig(dvdread)
    - pkgconfig(fontconfig)
    - pkgconfig(fribidi)
    - pkgconfig(GraphicsMagick)
    - pkgconfig(libpng)
setup      : |
    export MAGICK_CFLAGS=`GraphicsMagick-config --cppflags`
    export CFLAGS="$CFLAGS $MAGICK_CFLAGS"

    %configure  --disable-static
build      : |
    %make
install    : |
    %make_install
